# **Creating Automated Vendor Report Creation**

## **importing packages**

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
path = "C:\\Users\\hp\\Downloads\\Lead Report - 14th August.csv"

In [3]:
data = pd.read_csv(path)
data.shape[0]

378

In [4]:
data.columns.to_list()

['AT Source',
 'Followup Date',
 'WhatsApp 8 Delivered',
 'State',
 'Rejection Reason',
 'Primary Source Date',
 'Order Value',
 'WhatsApp 4 Read',
 'Customer ID Ameyo',
 'WhatsApp 6 Delivered',
 'WhatsApp 3 CTA Click',
 'web_referrer',
 'Eligible for WhatsApp',
 'WhatsApp 10 Read',
 'WhatsApp 1 Read',
 'Lead Priority',
 'Prospect Source',
 'Payout Source Campaign',
 'Prospect Source Details',
 'FnO Read Post Payment WhatsApp',
 'Lead Attribution',
 '3rd Connect Call Duration ',
 'Facebook',
 'transition e5_Selfie',
 'Lead Score',
 'Last Registration Date',
 'WhatsApp 7 Read',
 'transition e11_PAN Upload',
 'App id',
 'Sub Sub Disposition',
 'No of Connects',
 '3rd Connect Date Time',
 'No Of Callback Set',
 '4th Attempt Date Time',
 'WhatsApp 9 Read',
 'Dropoff Link 2',
 '3rd Attempt Date Time',
 'transition e15_Activated',
 'Dropoff Link 3',
 'Referee Mobile',
 'Email',
 'Outsourced Team',
 'DIY',
 'prospectid',
 'transition e10_Manual_Process',
 'web_refkeyword',
 'Call Back Date Time',
 'WhatsApp 8 CTA Click',
 'QualityScore01',
 'Do Not WhatsApp',
 'Lead Distribute',
 'First Connect',
 'WhatsApp Dropoff Flag',
 'Longitude',
 'Source Referrer URL',
 '1st Push Date',
 'Conversion Referrer URL',
 '2nd Connect Date Time',
 'WhatsApp 9 Delivered',
 'Owner Email Address',
 'WhatsApp 3 Read',
 'Pushed to TeleAccess',
 'Conversion Age',
 '3rd Attempt Call Duration',
 'WhatsApp Callback Date Time',
 'Activation Date',
 '5th Connect Call Duration ',
 'Opt In Details',
 'WhatsApp 9 Day',
 'Modified By',
 'Utm Adgroup',
 'Primary Source Campaign',
 'FnO Delivery Post Payment WhatsApp',
 'Dropoff Stage',
 'Last Connect',
 'Pan Number',
 'WhatsApp 5 Day',
 'Primary Source',
 'Lead Stage',
 'WhatsApp 3 min',
 'Push Date',
 'Verification Stage',
 'transition e14_Activation_Process',
 'Company',
 'Dropoff Link 5',
 'Registration Days Gap',
 'WhatsApp 8 Read',
 'ProspectReferee Email',
 'transition e12_eSign',
 'WhatsApp 6 CTA Click',
 'Deleted',
 'Referee Name',
 '2nd Attempt Call Duration ',
 'prospectactivitydate_min',
 'WhatsApp 10 Delivered',
 'WhatsApp 4 Delivered',
 '1st Connect Call Duration ',
 'LS Disposition',
 'WhatsApp 7 Delivered',
 'AT Prospect Source',
 'Selfie Delivery Post Payment WhatsApp',
 'modifiedby',
 'Last Source',
 'Callback Communication Type',
 'Dropoff Link 5 Timestamp',
 'WhatsApp 20 min',
 'Website',
 'Do Not Track',
 'Do Not Email',
 '1st Connect Owner - User',
 'transition e7_Bank',
 'Lead Origin',
 'GCLID',
 'WhatsApp 7 CTA Click',
 'Final Prospect Source Details',
 'transition e9_Digilocker',
 'Gtalk User',
 'LinkedIn',
 'WhatsApp 3 Delivered',
 'Eligible for Auto Callback',
 'Referral Read Post Payment WhatsApp',
 'Photo Url',
 'firstlandingpagesubmissionid',
 'Drip Trigger',
 'Dropoff Link 6 Timestamp',
 'Unsubscribe flag',
 'No of Attempts',
 '2nd Attempt Date Time',
 'Disposition',
 'Engagement Score',
 'Google Plus',
 'Address 2',
 'Dropoff Link 2 Timestamp',
 'Interested Product',
 'pageviewspervisit',
 'Address 1',
 'Primary Source Medium',
 'WhatsApp 7 min',
 'Created On',
 'Dropoff Link 4',
 'transition e13_Referral',
 'Referral Agent',
 'WhatsApp 5 min',
 'Eligible for Appsflyer Sync',
 'Assigned employee code',
 'Do Not Call',
 'Callback SMS Sent',
 'Sub Disposition',
 'transition e8_Personal Details',
 'Ekyc stage',
 'Payout Source Medium',
 'Mobile Number',
 'firstlandingpagesubmissiondate',
 'Esign Delivery Post Payment WhatsApp',
 '4th Connect Date Time',
 'WhatsApp 6 Read',
 'Referee Code',
 'Lead Source',
 'Eligible for WhatsApp On',
 'Kserve Team',
 'Lead Assignment Date',
 'First Attempt',
 'AT Source Medium',
 'Time Zone',
 'totalvisits',
 'Source Content',
 'WhatsApp 2 CTA Click',
 'WhatsApp 1 hr',
 'utm_keyword',
 'transition e6_Onscreen_Sign',
 'NewCustomFlag',
 'Flag',
 'UTM Term',
 'Callback Communication Date',
 'Referral link',
 'WhatsApp 5 Delivered',
 'ProspectReferee Mobile',
 'Notes',
 'Created By',
 'WhatsApp 5 Read',
 'WhatsApp 1 CTA Click',
 '5th Connect Date Time',
 'Dropoff Link 3 Timestamp',
 'Sales Groups',
 'Last Opt In Email Sent Date',
 'Esign Read Post Payment WhatsApp',
 '5th Attempt Date Time',
 'City',
 'Date of Birth',
 'Dropoff Link 1 Timestamp',
 'WhatsApp 2 Read',
 'WhatsApp 10 CTA Click',
 'Job Title',
 'WhatsApp 1 Delivered',
 '4th Connect Call Duration ',
 'Latitude',
 'Opt In Date',
 'transition e2_Email',
 'Do Not SMS',
 'Current Opt In Status',
 'Data Type',
 'Lead Name',
 'leadlastmodifiedon',
 'AMC plan',
 'Mailing Preferences',
 'Dropoff Link 1',
 'First Name',
 'Match Type',
 'Appsflyer id',
 'Zip',
 'Lead Owner',
 'transition e3_PAN',
 'WhatsApp 5 CTA Click',
 'Selfie Read Post Payment WhatsApp',
 'Total Payment Amount',
 'PAN Delivery Post Payment WhatsApp',
 'Last Name',
 'Prospect Creation Date',
 'Referral Delivery Post Payment WhatsApp',
 'PAN Read Post Payment WhatsApp',
 'Referee Email',
 'Campaign Name',
 'Placement',
 'Country',
 'Last Attempt',
 'Converted By',
 'Page URL',
 'Digi Read Post Payment WhatsApp',
 'Twitter',
 'Assigned Name',
 'Qualification Status',
 'term',
 'Digi Delivery Post Payment WhatsApp',
 'Brokerage account type',
 'Modified On',
 'Activation Time',
 'Reasons For Not Qualified',
 'Callback SMS Sent Date',
 'WhatsApp 3 Day',
 'Client Code',
 'Latest Enquiry Date',
 'Last Source Campaign',
 'Rejection Date Time',
 'ProspectReferee Name',
 'Utm Creative',
 'WhatsApp 7 Day',
 'Connectivity Status',
 'WhatsApp 9 CTA Click',
 'Dropoff Link 6',
 'WhatsApp 2 Delivered',
 'Comments',
 'statuscode',
 'Dropoff Link 4 Timestamp',
 'Post Payment WhatsApp',
 'Partner Code',
 'WhatsApp 23 hr',
 'Assigned Date',
 '2nd Dropoff',
 'source_content',
 '5th Attempt Call Duration',
 'Utm Device',
 'transition e4_Payment',
 'Last Source Medium',
 'leadsid',
 'Pushed to Drishti',
 '2nd Connect Call Duration',
 'WhatsApp 4 CTA Click',
 'Final Prospect Source',
 'Disposition Change Date',
 'Lead Number',
 'Drishti Push Date',
 'AT Source Campaign',
 '1st Attempt Call Duration',
 'eKYC Stage Code',
 '4th Attempt Call Duration',
 'transition e1_Mobile',
 'Skype Name',
 'WhatsApp Language',
 'Phone Number',
 'avgtimepervisit',
 'Source IP Address']

In [5]:
data_main = data[['prospectid', 'Mobile Number','Phone Number', 'Email', 'Primary Source Campaign', 'eKYC Stage Code', 'Total Payment Amount', 'Created On']]
data_main.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,eKYC Stage Code,Total Payment Amount,Created On
0,185b7b48-fd82-49db-b253-8206770b1479,8.447561e+09,8447561139,ajaysoni_007@hotmail.com,Market_Trader_YT_10_June_2024,e14_Activation_Process,01-01-1999 05:30,01-08-2024 16:23
1,ce02cb06-3bf6-47bc-8cc2-62586cd68c16,9.244853e+09,9244853449,NaN,abhishek_kar_YT_26th_April_2023,e1_Mobile,NaN,02-08-2024 15:28
2,e1cfddd8-8bc3-46c2-a709-e66b1bfe3f38,7.020090e+09,7020089671,suhelnaaz.120@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT_1_August...,e14_Activation_Process,01-01-2000 05:30,02-08-2024 00:09
3,1763c0b5-10cf-4324-b96f-519d010b75f5,7.358725e+09,7358725281,vishnu.k1821@gmail.com,INFO_Mindset_YT_3_August_2024,e4_Payment,NaN,06-08-2024 11:10
4,2523bfea-10ef-4a04-85da-99bcb59325a5,7.875520e+09,7875519593,sajjax@gmail.com,Shankar_Nath_YT_9_March_2024,e4_Payment,01-01-2415 05:30,07-08-2024 02:12

In [6]:
data_main.columns.to_list()

['prospectid',
 'Mobile Number',
 'Phone Number',
 'Email',
 'Primary Source Campaign',
 'eKYC Stage Code',
 'Total Payment Amount',
 'Created On']

## **Task 1 -Fill Mob No from Phone Number where Mob No is empty**

In [7]:
data_main.isnull().sum()

prospectid                   1
Mobile Number                1
Phone Number                 0
Email                       62
Primary Source Campaign      0
eKYC Stage Code              1
Total Payment Amount       178
Created On                   0
dtype: int64

In [8]:
# Function to extract the last 10 digits of the phone number
def extract_last_10_digits(phone):
    return str(phone)[-10:]

In [9]:
# Fill the null values in 'Mobile Number' with the last 10 digits of 'Phone Number'
data_main['Mobile Number'] = data_main.apply(
    lambda row: extract_last_10_digits(row['Phone Number']) if pd.isnull(row['Mobile Number']) or row['Mobile Number'] in ['None', 'nan'] else row['Mobile Number'],
    axis=1)

# Convert 'Mobile Number' to integer to remove any .0, then back to string
data_main['Mobile Number'] = data_main['Mobile Number'].apply(lambda x: str(int(float(x))))

In [10]:
data_main.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,eKYC Stage Code,Total Payment Amount,Created On
0,185b7b48-fd82-49db-b253-8206770b1479,8447561139,8447561139,ajaysoni_007@hotmail.com,Market_Trader_YT_10_June_2024,e14_Activation_Process,01-01-1999 05:30,01-08-2024 16:23
1,ce02cb06-3bf6-47bc-8cc2-62586cd68c16,9244853449,9244853449,NaN,abhishek_kar_YT_26th_April_2023,e1_Mobile,NaN,02-08-2024 15:28
2,e1cfddd8-8bc3-46c2-a709-e66b1bfe3f38,7020089671,7020089671,suhelnaaz.120@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT_1_August...,e14_Activation_Process,01-01-2000 05:30,02-08-2024 00:09
3,1763c0b5-10cf-4324-b96f-519d010b75f5,7358725281,7358725281,vishnu.k1821@gmail.com,INFO_Mindset_YT_3_August_2024,e4_Payment,NaN,06-08-2024 11:10
4,2523bfea-10ef-4a04-85da-99bcb59325a5,7875519593,7875519593,sajjax@gmail.com,Shankar_Nath_YT_9_March_2024,e4_Payment,01-01-2415 05:30,07-08-2024 02:12

## **Task 2 - Fill 'e2_Email' in eKYC Stage Code colunm**

In [11]:
data_main["eKYC Stage Code"] = data_main['eKYC Stage Code'].fillna('e2_Email')

In [12]:
data_main['eKYC Stage Code'].isnull().sum()

0

In [13]:
data_main.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,eKYC Stage Code,Total Payment Amount,Created On
0,185b7b48-fd82-49db-b253-8206770b1479,8447561139,8447561139,ajaysoni_007@hotmail.com,Market_Trader_YT_10_June_2024,e14_Activation_Process,01-01-1999 05:30,01-08-2024 16:23
1,ce02cb06-3bf6-47bc-8cc2-62586cd68c16,9244853449,9244853449,NaN,abhishek_kar_YT_26th_April_2023,e1_Mobile,NaN,02-08-2024 15:28
2,e1cfddd8-8bc3-46c2-a709-e66b1bfe3f38,7020089671,7020089671,suhelnaaz.120@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT_1_August...,e14_Activation_Process,01-01-2000 05:30,02-08-2024 00:09
3,1763c0b5-10cf-4324-b96f-519d010b75f5,7358725281,7358725281,vishnu.k1821@gmail.com,INFO_Mindset_YT_3_August_2024,e4_Payment,NaN,06-08-2024 11:10
4,2523bfea-10ef-4a04-85da-99bcb59325a5,7875519593,7875519593,sajjax@gmail.com,Shankar_Nath_YT_9_March_2024,e4_Payment,01-01-2415 05:30,07-08-2024 02:12

## **Task 3 - Adding Vendors to the data from  vendors sheet using VLOOKUP()**

In [14]:
csv_url = 'https://docs.google.com/spreadsheets/d/1osDdsySYQdoBZlguvbb_UCZt2wfRbQvhSj8B2qa_RgU/export?format=csv'

vendors_data = pd.read_csv(csv_url, header=None)
# Set the first row as the header
vendors_data.columns = vendors_data.iloc[1]
vendors_data = vendors_data.drop([0, 1]).reset_index(drop=True)
vendors_data.head()

1,Video Month,Channel,Video Link,CTC,Expected Lead counts as per CTC,YT Link,TG/YT1 Link,NaN,TG/YT1 Bitly,campaign,...,Agency,Status,TG Leads,YT Leads,Inf Leads,CPC,Old link,Old Bitly,old campaign name,NaN
0,Oct 23,Trade2Day,https://youtu.be/_akShxeeUXM,"30,000",7,https://www.mstock.com/sem-landing/zero-broker...,https://www.mstock.com/sem-landing/zero-broker...,Trade2Day,https://bit.ly/3ruhw6t,Trade2Day_TG_03rd_October,...,MRN,Paused,NaN,NaN,NaN,"30,000",NaN,NaN,NaN,NaN
1,Oct 23,Investment with Tarun,https://youtu.be/wuAg1NtzRIo?feature=shared,"40,000",9,https://www.mstock.com/sem-landing/zero-broker...,https://www.mstock.com/sem-landing/zero-broker...,Investment with Tarun,https://bit.ly/45gSFkc,Investment_with_Tarun_TG_03rd_October_2023,...,MRN,Paused,NaN,NaN,NaN,"40,000",NaN,NaN,NaN,NaN
2,Oct 23,Stock Market का Badshah (SMkB),https://youtu.be/WoCGzwg6Jwg,"20,000",4,https://www.mstock.com/sem-landing/zero-broker...,https://www.mstock.com/sem-landing/zero-broker...,Stock Market का Badshah (SMkB),https://bit.ly/3RKfr0U,Stock_Market_ka_Badshah_TG_03rd_October_2023,...,UTM,Paused,NaN,NaN,NaN,"20,000",NaN,NaN,NaN,NaN
3,Oct 23,Knowledge Jazz,https://youtu.be/U_T-gllIkww?si=PLyJ7PxUpWZHD2de,"65,000",14,https://www.mstock.com/sem-landing/zero-broker...,https://www.mstock.com/sem-landing/zero-broker...,Knowledge Jazz,https://bit.ly/46xKLnE,Knowledge_Jazz_TG_03rd_October_2023,...,UTM,Paused,29,NaN,NaN,"2,241",NaN,NaN,NaN,NaN
4,July 23,NaN,NaN,NaN,0,NaN,NaN,NaN,https://bit.ly/3ZH1FOs,trade_swings_TG_15th_july_2023,...,BS Enterprises,Paused,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
vendors_data_req = vendors_data[['TG/YT1 Bitly','campaign', 'Agency']]
vendors_data_req.columns= ['Bitly Link','Primary Source Campaign','agency']
vendors_data_req.head()

,Bitly Link,Primary Source Campaign,agency
0,https://bit.ly/3ruhw6t,Trade2Day_TG_03rd_October,MRN
1,https://bit.ly/45gSFkc,Investment_with_Tarun_TG_03rd_October_2023,MRN
2,https://bit.ly/3RKfr0U,Stock_Market_ka_Badshah_TG_03rd_October_2023,UTM
3,https://bit.ly/46xKLnE,Knowledge_Jazz_TG_03rd_October_2023,UTM
4,https://bit.ly/3ZH1FOs,trade_swings_TG_15th_july_2023,BS Enterprises

In [16]:
print(vendors_data_req.isna().sum())
print(vendors_data_req.shape[0])

Bitly Link                 280
Primary Source Campaign    281
agency                     477
dtype: int64
1142

In [17]:
vendors_data_req.dropna(how='any', inplace=True)
print(vendors_data_req.isna().sum())
print(vendors_data_req.shape[0])

Bitly Link                 0
Primary Source Campaign    0
agency                     0
dtype: int64
664

In [18]:
# Merge the data_main DataFrame with the vendors DataFrame on 'Primary Source Campaign'
data_merged = data_main.merge(vendors_data_req, on='Primary Source Campaign', how='left')
#data_merged.drop(['Bitly Link'], axis=1, inplace = True)
data_merged.tail()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
373,2a318f7a-72c0-4dda-886f-ec459d00766a,8750942138,8750942138,sannosaifi841@gmail.com,The_Global_Stories_YT1_2_August_2024,e15_Activated,1207.31,13-08-2024 20:57,https://bit.ly/4ccD5tl,BS
374,36205304-3304-474d-aea3-91a047afed4a,6395693675,6395693675,ssidd6673@gmail.com,The_Global_Stories_YT1_2_August_2024,e14_Activation_Process,0,13-08-2024 21:44,https://bit.ly/4ccD5tl,BS
375,NaN,7798899679,7798899679,mayamishra191271@gmail.com,Banking_Baba_YT1_1_August_2024,e4_Payment,0,13-08-2024 22:27,https://bit.ly/4dr6jpl,Raghuvansh
376,ad6c5053-fd00-4a6d-b159-d310b4a24b4a,8960557476,8960557476,amitkanaujiya7476@gmail.com,T_Daksh_Trading_YT1_4_August_2024,e14_Activation_Process,1207.31,13-08-2024 23:04,https://bit.ly/3Ww39tS,Raghuvansh
377,90167662-fca0-4e93-914d-83cfb11adf85,7050850677,7050850677,kumarravibalram@gmail.com,Atul_Patel_YT_13_August_2024,e4_Payment,NaN,13-08-2024 23:42,NaN,NaN

In [19]:
data_merged.shape[0]

378

In [20]:
data_merged.isna().sum()

prospectid                   1
Mobile Number                0
Phone Number                 0
Email                       62
Primary Source Campaign      0
eKYC Stage Code              0
Total Payment Amount       178
Created On                   0
Bitly Link                 202
agency                     202
dtype: int64

## **Task 4 -Creating a new column Lead Stage**

In [21]:
# a new column called lead stage 
# if eKYC has e12 OR e14 OR e15 then account opended AND Total Payment Amount is greater 100 then  
# else in proccess

In [22]:
#data_merged['Total Payment Amount'].fillna(0).astype(int)
data_merged['Total Payment Amount'] = pd.to_numeric(data_merged['Total Payment Amount'], errors='coerce').fillna(0).astype(int)
data_merged.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
0,185b7b48-fd82-49db-b253-8206770b1479,8447561139,8447561139,ajaysoni_007@hotmail.com,Market_Trader_YT_10_June_2024,e14_Activation_Process,0,01-08-2024 16:23,NaN,NaN
1,ce02cb06-3bf6-47bc-8cc2-62586cd68c16,9244853449,9244853449,NaN,abhishek_kar_YT_26th_April_2023,e1_Mobile,0,02-08-2024 15:28,NaN,NaN
2,e1cfddd8-8bc3-46c2-a709-e66b1bfe3f38,7020089671,7020089671,suhelnaaz.120@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT_1_August...,e14_Activation_Process,0,02-08-2024 00:09,NaN,NaN
3,1763c0b5-10cf-4324-b96f-519d010b75f5,7358725281,7358725281,vishnu.k1821@gmail.com,INFO_Mindset_YT_3_August_2024,e4_Payment,0,06-08-2024 11:10,NaN,NaN
4,2523bfea-10ef-4a04-85da-99bcb59325a5,7875519593,7875519593,sajjax@gmail.com,Shankar_Nath_YT_9_March_2024,e4_Payment,0,07-08-2024 02:12,NaN,NaN

In [23]:
data_merged.dtypes

prospectid                 object
Mobile Number              object
Phone Number                int64
Email                      object
Primary Source Campaign    object
eKYC Stage Code            object
Total Payment Amount        int32
Created On                 object
Bitly Link                 object
agency                     object
dtype: object

In [24]:
data_merged.insert(5, 'Lead Stage', None)
data_merged.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,Lead Stage,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
0,185b7b48-fd82-49db-b253-8206770b1479,8447561139,8447561139,ajaysoni_007@hotmail.com,Market_Trader_YT_10_June_2024,None,e14_Activation_Process,0,01-08-2024 16:23,NaN,NaN
1,ce02cb06-3bf6-47bc-8cc2-62586cd68c16,9244853449,9244853449,NaN,abhishek_kar_YT_26th_April_2023,None,e1_Mobile,0,02-08-2024 15:28,NaN,NaN
2,e1cfddd8-8bc3-46c2-a709-e66b1bfe3f38,7020089671,7020089671,suhelnaaz.120@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT_1_August...,None,e14_Activation_Process,0,02-08-2024 00:09,NaN,NaN
3,1763c0b5-10cf-4324-b96f-519d010b75f5,7358725281,7358725281,vishnu.k1821@gmail.com,INFO_Mindset_YT_3_August_2024,None,e4_Payment,0,06-08-2024 11:10,NaN,NaN
4,2523bfea-10ef-4a04-85da-99bcb59325a5,7875519593,7875519593,sajjax@gmail.com,Shankar_Nath_YT_9_March_2024,None,e4_Payment,0,07-08-2024 02:12,NaN,NaN

In [25]:
# Define the generate_lead_stage function
def generate_lead_stage(row):
    ekyc_stage_code = row['eKYC Stage Code']
    total_payment_amount = row['Total Payment Amount']
    
    if 'e12' in ekyc_stage_code or 'e14' in ekyc_stage_code or 'e15' in ekyc_stage_code:
        if total_payment_amount > 100:
            return '999-Account Opened'
        else:
            return 'L4-Account Opened'
    else:
        return 'L2-in process'

In [26]:
data_merged['Lead Stage'] = data_merged.apply(generate_lead_stage, axis=1)
data_merged.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,Lead Stage,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
0,185b7b48-fd82-49db-b253-8206770b1479,8447561139,8447561139,ajaysoni_007@hotmail.com,Market_Trader_YT_10_June_2024,L4-Account Opened,e14_Activation_Process,0,01-08-2024 16:23,NaN,NaN
1,ce02cb06-3bf6-47bc-8cc2-62586cd68c16,9244853449,9244853449,NaN,abhishek_kar_YT_26th_April_2023,L2-in process,e1_Mobile,0,02-08-2024 15:28,NaN,NaN
2,e1cfddd8-8bc3-46c2-a709-e66b1bfe3f38,7020089671,7020089671,suhelnaaz.120@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT_1_August...,L4-Account Opened,e14_Activation_Process,0,02-08-2024 00:09,NaN,NaN
3,1763c0b5-10cf-4324-b96f-519d010b75f5,7358725281,7358725281,vishnu.k1821@gmail.com,INFO_Mindset_YT_3_August_2024,L2-in process,e4_Payment,0,06-08-2024 11:10,NaN,NaN
4,2523bfea-10ef-4a04-85da-99bcb59325a5,7875519593,7875519593,sajjax@gmail.com,Shankar_Nath_YT_9_March_2024,L2-in process,e4_Payment,0,07-08-2024 02:12,NaN,NaN

In [27]:
# Making values in 'eKYC Stage Code' as null where values in 'Lead Stage' are 'L4-Account Opened', '999-Account Opened'
data_merged.loc[data_merged['Lead Stage'].isin(['L4-Account Opened', '999-Account Opened']), 'eKYC Stage Code'] = None
data_merged

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,Lead Stage,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
0,185b7b48-fd82-49db-b253-8206770b1479,8447561139,8447561139,ajaysoni_007@hotmail.com,Market_Trader_YT_10_June_2024,L4-Account Opened,None,0,01-08-2024 16:23,NaN,NaN
1,ce02cb06-3bf6-47bc-8cc2-62586cd68c16,9244853449,9244853449,NaN,abhishek_kar_YT_26th_April_2023,L2-in process,e1_Mobile,0,02-08-2024 15:28,NaN,NaN
2,e1cfddd8-8bc3-46c2-a709-e66b1bfe3f38,7020089671,7020089671,suhelnaaz.120@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT_1_August...,L4-Account Opened,None,0,02-08-2024 00:09,NaN,NaN
3,1763c0b5-10cf-4324-b96f-519d010b75f5,7358725281,7358725281,vishnu.k1821@gmail.com,INFO_Mindset_YT_3_August_2024,L2-in process,e4_Payment,0,06-08-2024 11:10,NaN,NaN
4,2523bfea-10ef-4a04-85da-99bcb59325a5,7875519593,7875519593,sajjax@gmail.com,Shankar_Nath_YT_9_March_2024,L2-in process,e4_Payment,0,07-08-2024 02:12,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
373,2a318f7a-72c0-4dda-886f-ec459d00766a,8750942138,8750942138,sannosaifi841@gmail.com,The_Global_Stories_YT1_2_August_2024,999-Account Opened,None,1207,13-08-2024 20:57,https://bit.ly/4ccD5tl,BS
374,36205304-3304-474d-aea3-91a047afed4a,6395693675,6395693675,ssidd6673@gmail.com,The_Global_Stories_YT1_2_August_2024,L4-Account Opened,None,0,13-08-2024 21:44,https://bit.ly/4ccD5tl,BS
375,NaN,7798899679,7798899679,mayamishra191271@gmail.com,Banking_Baba_YT1_1_August_2024,L2-in process,e4_Payment,0,13-08-2024 22:27,https://bit.ly/4dr6jpl,Raghuvansh
376,ad6c5053-fd00-4a6d-b159-d310b4a24b4a,8960557476,8960557476,amitkanaujiya7476@gmail.com,T_Daksh_Trading_YT1_4_August_2024,999-Account Opened,None,1207,13-08-2024 23:04,https://bit.ly/3Ww39tS,Raghuvansh
377,90167662-fca0-4e93-914d-83cfb11adf85,7050850677,7050850677,kumarravibalram@gmail.com,Atul_Patel_YT_13_August_2024,L2-in process,e4_Payment,0,13-08-2024 23:42,NaN,NaN

In [28]:
print(data_merged.isna().sum())
print(data_merged.shape[0])

prospectid                   1
Mobile Number                0
Phone Number                 0
Email                       62
Primary Source Campaign      0
Lead Stage                   0
eKYC Stage Code            160
Total Payment Amount         0
Created On                   0
Bitly Link                 202
agency                     202
dtype: int64
378

In [29]:
data_merged.dropna(subset=['agency'], inplace=True)
data_merged.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,Lead Stage,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
24,6e72952a-9e14-4f95-ba7b-b366a2e48c5b,8178267936,8178267936,arjunsingh858574@gmail.com,The_Global_Stories_YT1_2_August_2024,L4-Account Opened,None,0,09-08-2024 14:02,https://bit.ly/4ccD5tl,BS
26,d6c39c96-0cb7-45ae-82a6-d18226120eca,6261474187,6261474187,bapna7289@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT1_1_Augus...,L4-Account Opened,None,0,09-08-2024 09:55,https://bit.ly/3WMrJaV,Raghuvansh
29,13317736-bb4b-434a-aaba-a6cb2ce42047,6376209687,6376209687,shakilmhd24@gmail.com,Banking_Baba_YT1_1_August_2024,L2-in process,e4_Payment,0,08-08-2024 07:00,https://bit.ly/4dr6jpl,Raghuvansh
34,bdc9fc84-7d4c-46c8-9eac-a2e477f550f1,6386053955,6386053955,jitendrasingh25072003@gmail.com,Banking_Baba_YT1_1_August_2024,L4-Account Opened,None,0,07-08-2024 21:39,https://bit.ly/4dr6jpl,Raghuvansh
35,893f2fdb-52f2-499e-bec3-c360eade0c8d,6396549641,6396549641,chhayabansal914@gmail.com,Stock_Learners_YT1_10_July_2024,L4-Account Opened,None,0,07-08-2024 19:19,https://bit.ly/4cxteiM,Clickonik

In [30]:
data_merged.shape[0]

176

## **Task 5 - Extracting Dates and Dropping unused Columns**

In [31]:
data_merged['Created On'] = pd.to_datetime(data_merged['Created On'], format='%d-%m-%Y %H:%M', dayfirst=True).dt.date
data_merged.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,Lead Stage,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
24,6e72952a-9e14-4f95-ba7b-b366a2e48c5b,8178267936,8178267936,arjunsingh858574@gmail.com,The_Global_Stories_YT1_2_August_2024,L4-Account Opened,None,0,2024-08-09,https://bit.ly/4ccD5tl,BS
26,d6c39c96-0cb7-45ae-82a6-d18226120eca,6261474187,6261474187,bapna7289@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT1_1_Augus...,L4-Account Opened,None,0,2024-08-09,https://bit.ly/3WMrJaV,Raghuvansh
29,13317736-bb4b-434a-aaba-a6cb2ce42047,6376209687,6376209687,shakilmhd24@gmail.com,Banking_Baba_YT1_1_August_2024,L2-in process,e4_Payment,0,2024-08-08,https://bit.ly/4dr6jpl,Raghuvansh
34,bdc9fc84-7d4c-46c8-9eac-a2e477f550f1,6386053955,6386053955,jitendrasingh25072003@gmail.com,Banking_Baba_YT1_1_August_2024,L4-Account Opened,None,0,2024-08-07,https://bit.ly/4dr6jpl,Raghuvansh
35,893f2fdb-52f2-499e-bec3-c360eade0c8d,6396549641,6396549641,chhayabansal914@gmail.com,Stock_Learners_YT1_10_July_2024,L4-Account Opened,None,0,2024-08-07,https://bit.ly/4cxteiM,Clickonik

In [32]:
data_merged.head()

,prospectid,Mobile Number,Phone Number,Email,Primary Source Campaign,Lead Stage,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
24,6e72952a-9e14-4f95-ba7b-b366a2e48c5b,8178267936,8178267936,arjunsingh858574@gmail.com,The_Global_Stories_YT1_2_August_2024,L4-Account Opened,None,0,2024-08-09,https://bit.ly/4ccD5tl,BS
26,d6c39c96-0cb7-45ae-82a6-d18226120eca,6261474187,6261474187,bapna7289@gmail.com,Swing_Trader_-_The_Art_Of_Learning_YT1_1_Augus...,L4-Account Opened,None,0,2024-08-09,https://bit.ly/3WMrJaV,Raghuvansh
29,13317736-bb4b-434a-aaba-a6cb2ce42047,6376209687,6376209687,shakilmhd24@gmail.com,Banking_Baba_YT1_1_August_2024,L2-in process,e4_Payment,0,2024-08-08,https://bit.ly/4dr6jpl,Raghuvansh
34,bdc9fc84-7d4c-46c8-9eac-a2e477f550f1,6386053955,6386053955,jitendrasingh25072003@gmail.com,Banking_Baba_YT1_1_August_2024,L4-Account Opened,None,0,2024-08-07,https://bit.ly/4dr6jpl,Raghuvansh
35,893f2fdb-52f2-499e-bec3-c360eade0c8d,6396549641,6396549641,chhayabansal914@gmail.com,Stock_Learners_YT1_10_July_2024,L4-Account Opened,None,0,2024-08-07,https://bit.ly/4cxteiM,Clickonik

In [33]:
data_merged.drop(columns=['prospectid', 'Phone Number', 'Email'], inplace=True)
data_merged.head()

,Mobile Number,Primary Source Campaign,Lead Stage,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link,agency
24,8178267936,The_Global_Stories_YT1_2_August_2024,L4-Account Opened,None,0,2024-08-09,https://bit.ly/4ccD5tl,BS
26,6261474187,Swing_Trader_-_The_Art_Of_Learning_YT1_1_Augus...,L4-Account Opened,None,0,2024-08-09,https://bit.ly/3WMrJaV,Raghuvansh
29,6376209687,Banking_Baba_YT1_1_August_2024,L2-in process,e4_Payment,0,2024-08-08,https://bit.ly/4dr6jpl,Raghuvansh
34,6386053955,Banking_Baba_YT1_1_August_2024,L4-Account Opened,None,0,2024-08-07,https://bit.ly/4dr6jpl,Raghuvansh
35,6396549641,Stock_Learners_YT1_10_July_2024,L4-Account Opened,None,0,2024-08-07,https://bit.ly/4cxteiM,Clickonik

## **DON'T REQ - creating a pivot**

In [ ]:
data_merged.columns = data_merged.columns.astype(str)
data_merged['Total Payment Amount'] = data_merged['Total Payment Amount'].astype('int64')
data_merged.dtypes

In [ ]:
data_merged = data_merged.reset_index(drop=True)

In [ ]:
data_merged_pivot = pd.pivot_table(data_merged, 
                                   index='Primary Source Campaign',
                                   columns='Lead Stage',
                                   values='Mobile Number',
                                   aggfunc='count',
                                   fill_value=0)
data_merged_pivot

In [ ]:
print(data_merged_pivot.shape[0])
print(data_merged['Primary Source Campaign'].nunique())

In [ ]:
sum_row = data_merged_pivot.sum()
sum_row.name = 'Total'
data_merged_pivot = pd.concat([data_merged_pivot, pd.DataFrame(sum_row).T])

In [ ]:
data_merged_pivot = data_merged_pivot.reset_index()
data_merged_pivot.tail()

In [ ]:
# Rename the columns as needed
data_merged_pivot.columns.name = None
data_merged_pivot.columns = ['Primary Source Campaign', '999-Account Opened', 'L2-in process', 'L4-Account Opened']
data_merged_pivot.head()

## **DONT' REQ - merging the Bitly Link	with Pivot**

In [ ]:
# Create a dictionary to map 'Primary Source Campaign' to 'Bitly Link'
campaign_to_bitly = data_merged.set_index('Primary Source Campaign')['Bitly Link'].to_dict()

In [ ]:
# Add 'Bitly Link' column to data_merged_pivot by mapping
data_merged_pivot['Bitly Link'] = data_merged_pivot['Primary Source Campaign'].map(campaign_to_bitly)

In [ ]:
data_merged_pivot.shape[0]

In [ ]:
data_merged_pivot

## **DON'T REQ - Coverting all results to EXCEL File**

In [ ]:
with pd.ExcelWriter('C:\\Users\\hp\\Downloads\\Lead Report - 9th July output.xlsx', engine='xlsxwriter') as writer:
    data_merged.to_excel(writer, sheet_name='Data Cleaned', index=False)
    data_merged_pivot.to_excel(writer, sheet_name='Pivot', index=False)

## **Task 6 - Creating Agency wise Everything**

In [34]:
agency_groups = data_merged.groupby('agency')
agency_dfs = {agency: group.drop(columns=['agency']) for agency, group in agency_groups}

In [35]:
list_of_agency = []
list_of_agency_df = []
for agency, df in agency_dfs.items():
    list_of_agency.append(agency)
    list_of_agency_df.append(df)

print(list_of_agency)
#print(list_of_agency_df)

['BS', 'Clickonik', 'Digital Shoutouts Media', 'Golden Beacon', 'Raghuvansh']

In [36]:
list_of_agency_df[3]

,Mobile Number,Primary Source Campaign,Lead Stage,eKYC Stage Code,Total Payment Amount,Created On,Bitly Link
207,7747073411,Deekay_Financials_YT1_6_July_2024,L2-in process,e4_Payment,0,2024-08-09,https://bit.ly/3VYj8Az
212,6260475797,Deekay_Financials_YT1_6_July_2024,999-Account Opened,None,1207,2024-08-09,https://bit.ly/3VYj8Az
285,9131558108,Deekay_Financials_YT1_6_July_2024,999-Account Opened,None,1207,2024-08-11,https://bit.ly/3VYj8Az

In [37]:
list_of_agency_df[0].columns

Index(['Mobile Number', 'Primary Source Campaign', 'Lead Stage',
       'eKYC Stage Code', 'Total Payment Amount', 'Created On', 'Bitly Link'],
      dtype='object')

In [38]:
pivoted_df = []
for each_df in list_of_agency_df:
    each_df_pivot = pd.pivot_table(each_df, index='Primary Source Campaign', columns='Lead Stage', values='Mobile Number', aggfunc='count', fill_value=0)

    # adding a row of TOTAL
    sum_row = each_df_pivot.sum()
    sum_row.name = 'TOTAL'
    each_df_pivot = pd.concat([each_df_pivot, pd.DataFrame(sum_row).T])

    # Reset the index to make 'Primary Source Campaign' a regular column
    each_df_pivot = each_df_pivot.reset_index()

    # Ensure all desired columns are present
    required_columns = ['999-Account Opened', 'L2-in process', 'L4-Account Opened']
    for col in required_columns:
        if col not in each_df_pivot.columns:
            each_df_pivot[col] = 0
    
    # Reorder the columns
    # each_df_pivot = each_df_pivot[['Primary Source Campaign'] + required_columns]

    # renaming pivot column index to Primary Source Campaign
    each_df_pivot.rename(columns={'index':'Primary Source Campaign'}, inplace=True)
    
    # merging Bitly Links to it ---- # Create a dictionary to map 'Primary Source Campaign' to 'Bitly Link'
    campaign_to_bitly = each_df.set_index('Primary Source Campaign')['Bitly Link'].to_dict()

    # Add 'Bitly Link' column to data_merged_pivot by mapping
    each_df_pivot['Bitly Link'] = each_df_pivot['Primary Source Campaign'].map(campaign_to_bitly)
    
    # re-arranging the columns as per the requirements 
    each_df_pivot = each_df_pivot[["Bitly Link", "Primary Source Campaign", "999-Account Opened", "L2-in process", "L4-Account Opened"]]

    # Adding a new column 'Grand Total' which is the sum of the specified columns
    each_df_pivot["Grand Total"] = each_df_pivot[["999-Account Opened", "L2-in process", "L4-Account Opened"]].sum(axis=1)

    # adding the pivoted df in the list
    pivoted_df.append(each_df_pivot)

    # removing the column 'Bitly Link' from each df
    each_df.drop(['Bitly Link', 'Total Payment Amount'], axis=1, inplace=True)

# agency_pivotdf_dict = agency_dfs.copy()
# agency_pivotdf_dict.update(dict(zip(agency_dfs.keys(), pivoted_df)))

# Create a dictionary to store the original and pivoted DataFrames
agency_pivotdf_dict = {}
for key, original_df, pivoted in zip(agency_dfs.keys(), list_of_agency_df, pivoted_df):
    agency_pivotdf_dict[key] = [original_df, pivoted]
    
agency_dfs.update(agency_pivotdf_dict)

In [39]:
type(agency_pivotdf_dict['BS'])

list

In [40]:
import zipfile
from io import BytesIO
# Dictionary to store in-memory Excel files
excel_files = {}

# Iterate through the agency_pivotdf_dict to create in-memory Excel files
for agency_name, dfs in agency_pivotdf_dict.items():
    original_df, pivoted_df = dfs
    
    # Create a BytesIO object to hold the Excel file in memory
    excel_buffer = BytesIO()
    
    # Create an Excel writer object and add the DataFrames as sheets
    print('creating excel files...')
    with pd.ExcelWriter(excel_buffer, engine='xlsxwriter') as writer:
        original_df.to_excel(writer, sheet_name='Raw Data', index=False)
        pivoted_df.to_excel(writer, sheet_name='Summary', index=False)
    
    # Save the BytesIO object to the dictionary
    excel_files[agency_name] = excel_buffer

# Create a zip file containing all the in-memory Excel files
print('creating zip...')
zip_file_path = "mstock-data.zip"
with zipfile.ZipFile(zip_file_path, 'w') as zipf:
    for agency_name, excel_buffer in excel_files.items():
        # Seek to the beginning of the BytesIO object before writing
        excel_buffer.seek(0)
        # Write the BytesIO object to the zip file with the agency name as the file name
        zipf.writestr(f"{agency_name}.xlsx", excel_buffer.read())

print(f"All files have been zipped into {zip_file_path}")

creating excel files...
creating excel files...
creating excel files...
creating excel files...
creating excel files...
creating zip...
All files have been zipped into mstock-data.zip

In [41]:
#def craete_excel(dict):
with pd.ExcelWriter('excel files//output.xlsx', engine='xlsxwriter') as writer:
    for key, value in agency_pivotdf_dict.items():
        value.to_excel(writer, sheet_name=str(key), index=False)

AttributeError: 'list' object has no attribute 'to_excel'

In [ ]:
pd.pivot_table(list_of_agency_df[0], index='Primary Source Campaign', columns='Lead Stage', values='Mobile Number', aggfunc='count', fill_value=0)

In [ ]:
agency_dfs.keys()